version: '3'

tasks:
  install:
    deps: [install/proxy]

  build:
    deps:
      - build/extension/debug
      - build/proxy

  build/proxy:
    desc: "build proxy server"
    dir: hiproxy
    vars:
      TARGET_DIR: ../build
    cmd: |
      HIPROXY_VERSION=$(git describe --tags --long)
      echo $HIPROXY_VERSION
      mkdir -p {{.TARGET_DIR}}
      go build -ldflags "-X 'main.version=$HIPROXY_VERSION-local' -s -w" -o {{.TARGET_DIR}} ./...

  install/proxy:
    desc: "install proxy server"
    dir: hiproxy
    cmd: |
      HIPROXY_VERSION=$(git describe --tags --long)
      echo $HIPROXY_VERSION
      go install -ldflags "-X 'main.version=$HIPROXY_VERSION-local' -s -w" ./...

  build/extension/debug:
    silent: true
    dir: extension
    vars:
      ARTIFACTS_DIR: ../build/artifacts/extension
      TARGET_DIR: ../build
    cmds:
      - rm -rf {{.TARGET_DIR}}/headit.app
      - mkdir -p {{.ARTIFACTS_DIR}}
      - mkdir -p {{.TARGET_DIR}}
      - xcodebuild -scheme headit -configuration Debug -target headit -archivePath {{.ARTIFACTS_DIR}}/extension.xcarchive archive
      - xcodebuild -exportArchive -archivePath {{.ARTIFACTS_DIR}}/extension.xcarchive -exportOptionsPlist 'headit Extension/Info.plist' -exportPath {{.ARTIFACTS_DIR}}
      - cp -r {{.ARTIFACTS_DIR}}/headit.app {{.TARGET_DIR}}

