### Set "X-Test-Header: 12345" to all requests
POST localhost:9096
Content-Type: application/json

{
  "rules": [{
    "base_url": "admin-dev.cp.sbercloud.dev",
    "add_headers": {
      "X-Test-Header": "12345"
    }
  }]
}

### Check result
GET https://echo.free.beeceptor.com
